### ISSUE TITLE
User history

### ISSUE THREAD

**Issue by berenice-b** [olivdums/thebikingproject#19]
### Why

A user should be able to view his orders' history

### To Do

- [x] We should use the orders model (#index) filtered by user_id
- [x] View displays orders index
- [x] Add button to access users's history
- [x] If there are no orders yet, a notice should appear saying: "You did not order anything yet." A button should be added saying "Start shopping now"  redirect_to products#index
- [x] Page looks well designed and professional

**Comment by nikkiHelloThp** [comment]
page look weel designed and professional ;)
