### ISSUE TITLE
User edit profile information

### ISSUE THREAD

**Issue by berenice-b** [olivdums/thebikingproject#23]
### Why

A user should be able to edit his profile information

### To Do

- [x] We should display edit form related to profile model
- [x] Display addresses linked to the current user 
- [x] Add edit or delete options for addresses (related to address model)
- [x] Button with link to Devise edit info
- [ ] View looks nice and professional

### Must Have

- [x] Address model

**Comment by nikkiHelloThp** [comment]
Profile deleted
